# Generated by Django 4.2.17 on 2025-02-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='file',
        ),
        migrations.AddField(
            model_name='homework',
            name='content',
            field=models.TextField(default='temp-content'),
            preserve_default=False,
        ),
    ]
