# Generated by Django 4.2.17 on 2025-02-05 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('homework', '0004_remove_homework_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='lessons.subject'),
            preserve_default=False,
        ),
    ]
