# Generated by Django 4.2.17 on 2025-02-05 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_homework_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='notes',
            new_name='student_notes',
        ),
        migrations.AddField(
            model_name='homework',
            name='teacher_notes',
            field=models.TextField(blank=True),
        ),
    ]
