# Generated by Django 4.2.17 on 2025-02-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_status',
            field=models.IntegerField(choices=[(0, 'Approved'), (1, 'Reported')], default=0),
        ),
    ]
