# Generated by Django 4.2.17 on 2025-01-28 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='author',
            new_name='teacher',
        ),
    ]
