# Generated by Django 4.2.17 on 2025-01-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_rename_teacher_comment_commenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='status',
            new_name='lesson_status',
        ),
    ]
