# Generated by Django 4.2.17 on 2025-01-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_rename_status_lesson_lesson_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_status',
            field=models.IntegerField(choices=[(0, 'Published'), (1, 'Reported')], default=0),
        ),
    ]
